/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeedge/sedna/pkg/apis/sedna/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeObjectQueryJobs implements ObjectQueryJobInterface
type FakeObjectQueryJobs struct {
	Fake *FakeSednaV1alpha1
	ns   string
}

var objectqueryjobsResource = schema.GroupVersionResource{Group: "sedna.io", Version: "v1alpha1", Resource: "objectqueryjobs"}

var objectqueryjobsKind = schema.GroupVersionKind{Group: "sedna.io", Version: "v1alpha1", Kind: "ObjectQueryJob"}

// Get takes name of the objectQueryJob, and returns the corresponding objectQueryJob object, and an error if there is any.
func (c *FakeObjectQueryJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ObjectQueryJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(objectqueryjobsResource, c.ns, name), &v1alpha1.ObjectQueryJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObjectQueryJob), err
}

// List takes label and field selectors, and returns the list of ObjectQueryJobs that match those selectors.
func (c *FakeObjectQueryJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ObjectQueryJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(objectqueryjobsResource, objectqueryjobsKind, c.ns, opts), &v1alpha1.ObjectQueryJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ObjectQueryJobList{ListMeta: obj.(*v1alpha1.ObjectQueryJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ObjectQueryJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested objectQueryJobs.
func (c *FakeObjectQueryJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(objectqueryjobsResource, c.ns, opts))

}

// Create takes the representation of a objectQueryJob and creates it.  Returns the server's representation of the objectQueryJob, and an error, if there is any.
func (c *FakeObjectQueryJobs) Create(ctx context.Context, objectQueryJob *v1alpha1.ObjectQueryJob, opts v1.CreateOptions) (result *v1alpha1.ObjectQueryJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(objectqueryjobsResource, c.ns, objectQueryJob), &v1alpha1.ObjectQueryJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObjectQueryJob), err
}

// Update takes the representation of a objectQueryJob and updates it. Returns the server's representation of the objectQueryJob, and an error, if there is any.
func (c *FakeObjectQueryJobs) Update(ctx context.Context, objectQueryJob *v1alpha1.ObjectQueryJob, opts v1.UpdateOptions) (result *v1alpha1.ObjectQueryJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(objectqueryjobsResource, c.ns, objectQueryJob), &v1alpha1.ObjectQueryJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObjectQueryJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeObjectQueryJobs) UpdateStatus(ctx context.Context, objectQueryJob *v1alpha1.ObjectQueryJob, opts v1.UpdateOptions) (*v1alpha1.ObjectQueryJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(objectqueryjobsResource, "status", c.ns, objectQueryJob), &v1alpha1.ObjectQueryJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObjectQueryJob), err
}

// Delete takes name of the objectQueryJob and deletes it. Returns an error if one occurs.
func (c *FakeObjectQueryJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(objectqueryjobsResource, c.ns, name), &v1alpha1.ObjectQueryJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeObjectQueryJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(objectqueryjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ObjectQueryJobList{})
	return err
}

// Patch applies the patch and returns the patched objectQueryJob.
func (c *FakeObjectQueryJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ObjectQueryJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(objectqueryjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ObjectQueryJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObjectQueryJob), err
}
