apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zoo1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: follower
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zoo1
  externalIPs:
    - MASTER_NODE_IP
