apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: http-9092
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: ClusterIP
  externalIPs:
    - MASTER_NODE_IP