apiVersion: v1
kind: PersistentVolume
metadata:
  name: reid-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: NFS_PATH
    server: MASTER_NODE_IP # ip of the node hosting the NFS server (the master, ideally)